version: "3"

services:

  swarm-ui:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
#    networks:
#      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/portainer:/data
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - ca.itm.dm=Util
        - ca.itm.description=Cluster Web UI
      placement:
        constraints: 
          - node.labels.usage==util

