version: "3"

networks:
  elk:
   external: true

services:

  logspout:
    image: gliderlabs/logspout:latest
    networks:
      - elk
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      syslog://logstash:51415
    deploy:
      mode: global
