version: "3"

services:

  filebeat:
    image: localhost:5000/myfilebeat 
    networks:
      - elk
    volumes:
      - /var/lib/docker/containers/:/host-logs
    deploy:
      mode: global

networks:
  elk:
    external: true
